### PR TITLE
Fetches Repository info from Github

### LINKED ISSUE #34: Fetch Github Info
### Is your feature request related to a problem? Please describe

No problem

### Describe the solution you'd like

When a Github repo url is submitted we should be able to fetch information about the repo

### Describe alternatives you've considered

No alternatives

### Addtional Context

_No response_

### PR DESCRIPTION
**Pull request by DarrylBrooks97**
Resolves #34 
- [x] On button submit create github entry on supabase

### CODE REVIEW

**Comment by Garrett1Tolbert** [comment]
Still need some sort of loading state when getting repos

**Comment by blaccsmith** [comment]
The graphql api has been created to fetch resources. Please update SWR to fetch from the new api

**Comment by Garrett1Tolbert** [comment]
Last step to this PR ✨
- [ ] only show repos that have been verified

**Review by blaccsmith — APPROVED** [review]
LGTM

**Pull request merged**
